// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/element.proto

package test;

public interface BattleOrBuilder extends
    // @@protoc_insertion_point(interface_extends:test.Battle)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int32 id = 1;</code>
   */
  int getId();
}
