// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/element.proto

package test;

public interface ElementOrBuilder extends
    // @@protoc_insertion_point(interface_extends:test.Element)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional bool bool_value = 1;</code>
   */
  boolean getBoolValue();

  /**
   * <code>optional float float_value = 2;</code>
   */
  float getFloatValue();

  /**
   * <code>optional double double_value = 3;</code>
   */
  double getDoubleValue();

  /**
   * <code>optional int32 int32_value = 4;</code>
   */
  int getInt32Value();

  /**
   * <code>optional int64 int64_value = 5;</code>
   */
  long getInt64Value();

  /**
   * <code>optional uint32 uint32_value = 6;</code>
   */
  int getUint32Value();

  /**
   * <code>optional uint64 uint64_value = 7;</code>
   */
  long getUint64Value();

  /**
   * <code>optional sint32 sint32_value = 8;</code>
   */
  int getSint32Value();

  /**
   * <code>optional sint64 sint64_value = 9;</code>
   */
  long getSint64Value();

  /**
   * <code>optional fixed32 fixed32_value = 10;</code>
   */
  int getFixed32Value();

  /**
   * <code>optional fixed64 fixed64_value = 11;</code>
   */
  long getFixed64Value();

  /**
   * <code>optional sfixed32 sfixed32_value = 12;</code>
   */
  int getSfixed32Value();

  /**
   * <code>optional sfixed64 sfixed64_value = 13;</code>
   */
  long getSfixed64Value();

  /**
   * <code>optional string string_value = 14;</code>
   */
  java.lang.String getStringValue();
  /**
   * <code>optional string string_value = 14;</code>
   */
  com.google.protobuf.ByteString
      getStringValueBytes();

  /**
   * <code>optional bytes bytes_value = 15;</code>
   */
  com.google.protobuf.ByteString getBytesValue();

  /**
   * <code>optional .test.Element.Type type = 16;</code>
   */
  boolean hasType();
  /**
   * <code>optional .test.Element.Type type = 16;</code>
   */
  test.Element.Type getType();
  /**
   * <code>optional .test.Element.Type type = 16;</code>
   */
  test.Element.TypeOrBuilder getTypeOrBuilder();

  /**
   * <code>optional .test.Battle.Player player = 17;</code>
   */
  boolean hasPlayer();
  /**
   * <code>optional .test.Battle.Player player = 17;</code>
   */
  test.Battle.Player getPlayer();
  /**
   * <code>optional .test.Battle.Player player = 17;</code>
   */
  test.Battle.PlayerOrBuilder getPlayerOrBuilder();

  /**
   * <code>optional .test.Battle.Skill skill = 18;</code>
   */
  boolean hasSkill();
  /**
   * <code>optional .test.Battle.Skill skill = 18;</code>
   */
  test.Battle.Skill getSkill();
  /**
   * <code>optional .test.Battle.Skill skill = 18;</code>
   */
  test.Battle.SkillOrBuilder getSkillOrBuilder();

  /**
   * <code>optional bool union_bool_value = 19;</code>
   */
  boolean getUnionBoolValue();

  /**
   * <code>optional float union_float_value = 20;</code>
   */
  float getUnionFloatValue();

  /**
   * <code>optional double union_double_value = 21;</code>
   */
  double getUnionDoubleValue();

  /**
   * <code>optional int32 union_int32_value = 22;</code>
   */
  int getUnionInt32Value();

  /**
   * <code>optional int64 union_int64_value = 23;</code>
   */
  long getUnionInt64Value();

  /**
   * <code>optional uint32 union_uint32_value = 24;</code>
   */
  int getUnionUint32Value();

  /**
   * <code>optional uint64 union_uint64_value = 25;</code>
   */
  long getUnionUint64Value();

  /**
   * <code>optional sint32 union_sint32_value = 26;</code>
   */
  int getUnionSint32Value();

  /**
   * <code>optional sint64 union_sint64_value = 27;</code>
   */
  long getUnionSint64Value();

  /**
   * <code>optional fixed32 union_fixed32_value = 28;</code>
   */
  int getUnionFixed32Value();

  /**
   * <code>optional fixed64 union_fixed64_value = 29;</code>
   */
  long getUnionFixed64Value();

  /**
   * <code>optional sfixed32 union_sfixed32_value = 30;</code>
   */
  int getUnionSfixed32Value();

  /**
   * <code>optional sfixed64 union_sfixed64_value = 31;</code>
   */
  long getUnionSfixed64Value();

  /**
   * <code>optional string union_string_value = 32;</code>
   */
  java.lang.String getUnionStringValue();
  /**
   * <code>optional string union_string_value = 32;</code>
   */
  com.google.protobuf.ByteString
      getUnionStringValueBytes();

  /**
   * <code>optional bytes union_bytes_value = 33;</code>
   */
  com.google.protobuf.ByteString getUnionBytesValue();

  /**
   * <code>optional .test.Element.Type union_type = 34;</code>
   */
  test.Element.Type getUnionType();
  /**
   * <code>optional .test.Element.Type union_type = 34;</code>
   */
  test.Element.TypeOrBuilder getUnionTypeOrBuilder();

  /**
   * <code>optional .test.Battle.Player union_player = 35;</code>
   */
  test.Battle.Player getUnionPlayer();
  /**
   * <code>optional .test.Battle.Player union_player = 35;</code>
   */
  test.Battle.PlayerOrBuilder getUnionPlayerOrBuilder();

  /**
   * <code>optional .test.Battle.Skill union_skill = 36;</code>
   */
  test.Battle.Skill getUnionSkill();
  /**
   * <code>optional .test.Battle.Skill union_skill = 36;</code>
   */
  test.Battle.SkillOrBuilder getUnionSkillOrBuilder();

  /**
   * <code>repeated bool bool_values = 37;</code>
   */
  java.util.List<java.lang.Boolean> getBoolValuesList();
  /**
   * <code>repeated bool bool_values = 37;</code>
   */
  int getBoolValuesCount();
  /**
   * <code>repeated bool bool_values = 37;</code>
   */
  boolean getBoolValues(int index);

  /**
   * <code>repeated float float_values = 38;</code>
   */
  java.util.List<java.lang.Float> getFloatValuesList();
  /**
   * <code>repeated float float_values = 38;</code>
   */
  int getFloatValuesCount();
  /**
   * <code>repeated float float_values = 38;</code>
   */
  float getFloatValues(int index);

  /**
   * <code>repeated double double_values = 39;</code>
   */
  java.util.List<java.lang.Double> getDoubleValuesList();
  /**
   * <code>repeated double double_values = 39;</code>
   */
  int getDoubleValuesCount();
  /**
   * <code>repeated double double_values = 39;</code>
   */
  double getDoubleValues(int index);

  /**
   * <code>repeated int32 int32_values = 40;</code>
   */
  java.util.List<java.lang.Integer> getInt32ValuesList();
  /**
   * <code>repeated int32 int32_values = 40;</code>
   */
  int getInt32ValuesCount();
  /**
   * <code>repeated int32 int32_values = 40;</code>
   */
  int getInt32Values(int index);

  /**
   * <code>repeated int64 int64_values = 41;</code>
   */
  java.util.List<java.lang.Long> getInt64ValuesList();
  /**
   * <code>repeated int64 int64_values = 41;</code>
   */
  int getInt64ValuesCount();
  /**
   * <code>repeated int64 int64_values = 41;</code>
   */
  long getInt64Values(int index);

  /**
   * <code>repeated uint32 uint32_values = 42;</code>
   */
  java.util.List<java.lang.Integer> getUint32ValuesList();
  /**
   * <code>repeated uint32 uint32_values = 42;</code>
   */
  int getUint32ValuesCount();
  /**
   * <code>repeated uint32 uint32_values = 42;</code>
   */
  int getUint32Values(int index);

  /**
   * <code>repeated uint64 uint64_values = 43;</code>
   */
  java.util.List<java.lang.Long> getUint64ValuesList();
  /**
   * <code>repeated uint64 uint64_values = 43;</code>
   */
  int getUint64ValuesCount();
  /**
   * <code>repeated uint64 uint64_values = 43;</code>
   */
  long getUint64Values(int index);

  /**
   * <code>repeated sint32 sint32_values = 44;</code>
   */
  java.util.List<java.lang.Integer> getSint32ValuesList();
  /**
   * <code>repeated sint32 sint32_values = 44;</code>
   */
  int getSint32ValuesCount();
  /**
   * <code>repeated sint32 sint32_values = 44;</code>
   */
  int getSint32Values(int index);

  /**
   * <code>repeated sint64 sint64_values = 45;</code>
   */
  java.util.List<java.lang.Long> getSint64ValuesList();
  /**
   * <code>repeated sint64 sint64_values = 45;</code>
   */
  int getSint64ValuesCount();
  /**
   * <code>repeated sint64 sint64_values = 45;</code>
   */
  long getSint64Values(int index);

  /**
   * <code>repeated fixed32 fixed32_values = 46;</code>
   */
  java.util.List<java.lang.Integer> getFixed32ValuesList();
  /**
   * <code>repeated fixed32 fixed32_values = 46;</code>
   */
  int getFixed32ValuesCount();
  /**
   * <code>repeated fixed32 fixed32_values = 46;</code>
   */
  int getFixed32Values(int index);

  /**
   * <code>repeated fixed64 fixed64_values = 47;</code>
   */
  java.util.List<java.lang.Long> getFixed64ValuesList();
  /**
   * <code>repeated fixed64 fixed64_values = 47;</code>
   */
  int getFixed64ValuesCount();
  /**
   * <code>repeated fixed64 fixed64_values = 47;</code>
   */
  long getFixed64Values(int index);

  /**
   * <code>repeated sfixed32 sfixed32_values = 48;</code>
   */
  java.util.List<java.lang.Integer> getSfixed32ValuesList();
  /**
   * <code>repeated sfixed32 sfixed32_values = 48;</code>
   */
  int getSfixed32ValuesCount();
  /**
   * <code>repeated sfixed32 sfixed32_values = 48;</code>
   */
  int getSfixed32Values(int index);

  /**
   * <code>repeated sfixed64 sfixed64_values = 49;</code>
   */
  java.util.List<java.lang.Long> getSfixed64ValuesList();
  /**
   * <code>repeated sfixed64 sfixed64_values = 49;</code>
   */
  int getSfixed64ValuesCount();
  /**
   * <code>repeated sfixed64 sfixed64_values = 49;</code>
   */
  long getSfixed64Values(int index);

  /**
   * <code>repeated string string_values = 50;</code>
   */
  com.google.protobuf.ProtocolStringList
      getStringValuesList();
  /**
   * <code>repeated string string_values = 50;</code>
   */
  int getStringValuesCount();
  /**
   * <code>repeated string string_values = 50;</code>
   */
  java.lang.String getStringValues(int index);
  /**
   * <code>repeated string string_values = 50;</code>
   */
  com.google.protobuf.ByteString
      getStringValuesBytes(int index);

  /**
   * <code>repeated bytes bytes_values = 51;</code>
   */
  java.util.List<com.google.protobuf.ByteString> getBytesValuesList();
  /**
   * <code>repeated bytes bytes_values = 51;</code>
   */
  int getBytesValuesCount();
  /**
   * <code>repeated bytes bytes_values = 51;</code>
   */
  com.google.protobuf.ByteString getBytesValues(int index);

  /**
   * <code>repeated .test.Element.Type types = 52;</code>
   */
  java.util.List<test.Element.Type> 
      getTypesList();
  /**
   * <code>repeated .test.Element.Type types = 52;</code>
   */
  test.Element.Type getTypes(int index);
  /**
   * <code>repeated .test.Element.Type types = 52;</code>
   */
  int getTypesCount();
  /**
   * <code>repeated .test.Element.Type types = 52;</code>
   */
  java.util.List<? extends test.Element.TypeOrBuilder> 
      getTypesOrBuilderList();
  /**
   * <code>repeated .test.Element.Type types = 52;</code>
   */
  test.Element.TypeOrBuilder getTypesOrBuilder(
      int index);

  /**
   * <code>repeated .test.Battle.Player players = 53;</code>
   */
  java.util.List<test.Battle.Player> 
      getPlayersList();
  /**
   * <code>repeated .test.Battle.Player players = 53;</code>
   */
  test.Battle.Player getPlayers(int index);
  /**
   * <code>repeated .test.Battle.Player players = 53;</code>
   */
  int getPlayersCount();
  /**
   * <code>repeated .test.Battle.Player players = 53;</code>
   */
  java.util.List<? extends test.Battle.PlayerOrBuilder> 
      getPlayersOrBuilderList();
  /**
   * <code>repeated .test.Battle.Player players = 53;</code>
   */
  test.Battle.PlayerOrBuilder getPlayersOrBuilder(
      int index);

  /**
   * <code>repeated .test.Battle.Skill skills = 54;</code>
   */
  java.util.List<test.Battle.Skill> 
      getSkillsList();
  /**
   * <code>repeated .test.Battle.Skill skills = 54;</code>
   */
  test.Battle.Skill getSkills(int index);
  /**
   * <code>repeated .test.Battle.Skill skills = 54;</code>
   */
  int getSkillsCount();
  /**
   * <code>repeated .test.Battle.Skill skills = 54;</code>
   */
  java.util.List<? extends test.Battle.SkillOrBuilder> 
      getSkillsOrBuilderList();
  /**
   * <code>repeated .test.Battle.Skill skills = 54;</code>
   */
  test.Battle.SkillOrBuilder getSkillsOrBuilder(
      int index);

  /**
   * <code>optional .test.Response resp = 55;</code>
   */
  int getRespValue();
  /**
   * <code>optional .test.Response resp = 55;</code>
   */
  test.Response getResp();

  public test.Element.UnionCase getUnionCase();
}
