// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/element.proto

package test;

public final class ElementDef {
  private ElementDef() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_test_Battle_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_test_Battle_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_test_Battle_Player_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_test_Battle_Player_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_test_Battle_Player_SkillEntry_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_test_Battle_Player_SkillEntry_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_test_Battle_Skill_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_test_Battle_Skill_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_test_Element_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_test_Element_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_test_Element_Type_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_test_Element_Type_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024protos/element.proto\022\004test\"\325\001\n\006Battle\022" +
      "\n\n\002id\030\001 \001(\005\032\251\001\n\006Player\022\n\n\002id\030\001 \001(\005\022\014\n\004na" +
      "me\030\002 \001(\t\022\t\n\001x\030\003 \001(\002\022\t\n\001y\030\004 \001(\002\022-\n\005skill\030" +
      "\005 \003(\0132\036.test.Battle.Player.SkillEntry\032@\n" +
      "\nSkillEntry\022\013\n\003key\030\001 \001(\005\022!\n\005value\030\002 \001(\0132" +
      "\022.test.Battle.Skill:\0028\001\032\023\n\005Skill\022\n\n\002id\030\001" +
      " \001(\005\"\202\014\n\007Element\022\022\n\nbool_value\030\001 \001(\010\022\023\n\013" +
      "float_value\030\002 \001(\002\022\024\n\014double_value\030\003 \001(\001\022" +
      "\023\n\013int32_value\030\004 \001(\005\022\023\n\013int64_value\030\005 \001(" +
      "\003\022\024\n\014uint32_value\030\006 \001(\r\022\024\n\014uint64_value\030",
      "\007 \001(\004\022\024\n\014sint32_value\030\010 \001(\021\022\024\n\014sint64_va" +
      "lue\030\t \001(\022\022\025\n\rfixed32_value\030\n \001(\007\022\025\n\rfixe" +
      "d64_value\030\013 \001(\006\022\026\n\016sfixed32_value\030\014 \001(\017\022" +
      "\026\n\016sfixed64_value\030\r \001(\020\022\024\n\014string_value\030" +
      "\016 \001(\t\022\023\n\013bytes_value\030\017 \001(\014\022 \n\004type\030\020 \001(\013" +
      "2\022.test.Element.Type\022#\n\006player\030\021 \001(\0132\023.t" +
      "est.Battle.Player\022!\n\005skill\030\022 \001(\0132\022.test." +
      "Battle.Skill\022\032\n\020union_bool_value\030\023 \001(\010H\000" +
      "\022\033\n\021union_float_value\030\024 \001(\002H\000\022\034\n\022union_d" +
      "ouble_value\030\025 \001(\001H\000\022\033\n\021union_int32_value",
      "\030\026 \001(\005H\000\022\033\n\021union_int64_value\030\027 \001(\003H\000\022\034\n" +
      "\022union_uint32_value\030\030 \001(\rH\000\022\034\n\022union_uin" +
      "t64_value\030\031 \001(\004H\000\022\034\n\022union_sint32_value\030" +
      "\032 \001(\021H\000\022\034\n\022union_sint64_value\030\033 \001(\022H\000\022\035\n" +
      "\023union_fixed32_value\030\034 \001(\007H\000\022\035\n\023union_fi" +
      "xed64_value\030\035 \001(\006H\000\022\036\n\024union_sfixed32_va" +
      "lue\030\036 \001(\017H\000\022\036\n\024union_sfixed64_value\030\037 \001(" +
      "\020H\000\022\034\n\022union_string_value\030  \001(\tH\000\022\033\n\021uni" +
      "on_bytes_value\030! \001(\014H\000\022(\n\nunion_type\030\" \001" +
      "(\0132\022.test.Element.TypeH\000\022+\n\014union_player",
      "\030# \001(\0132\023.test.Battle.PlayerH\000\022)\n\013union_s" +
      "kill\030$ \001(\0132\022.test.Battle.SkillH\000\022\023\n\013bool" +
      "_values\030% \003(\010\022\024\n\014float_values\030& \003(\002\022\025\n\rd" +
      "ouble_values\030\' \003(\001\022\024\n\014int32_values\030( \003(\005" +
      "\022\024\n\014int64_values\030) \003(\003\022\025\n\ruint32_values\030" +
      "* \003(\r\022\025\n\ruint64_values\030+ \003(\004\022\025\n\rsint32_v" +
      "alues\030, \003(\021\022\025\n\rsint64_values\030- \003(\022\022\026\n\016fi" +
      "xed32_values\030. \003(\007\022\026\n\016fixed64_values\030/ \003" +
      "(\006\022\027\n\017sfixed32_values\0300 \003(\017\022\027\n\017sfixed64_" +
      "values\0301 \003(\020\022\025\n\rstring_values\0302 \003(\t\022\024\n\014b",
      "ytes_values\0303 \003(\014\022!\n\005types\0304 \003(\0132\022.test." +
      "Element.Type\022$\n\007players\0305 \003(\0132\023.test.Bat" +
      "tle.Player\022\"\n\006skills\0306 \003(\0132\022.test.Battle" +
      ".Skill\022\034\n\004resp\0307 \001(\0162\016.test.Response\032\022\n\004" +
      "Type\022\n\n\002id\030\001 \001(\005B\007\n\005union*\032\n\010Response\022\006\n" +
      "\002OK\020\000\022\006\n\002NO\020\001B\016B\nElementDefP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_test_Battle_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_test_Battle_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_test_Battle_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_test_Battle_Player_descriptor =
      internal_static_test_Battle_descriptor.getNestedTypes().get(0);
    internal_static_test_Battle_Player_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_test_Battle_Player_descriptor,
        new java.lang.String[] { "Id", "Name", "X", "Y", "Skill", });
    internal_static_test_Battle_Player_SkillEntry_descriptor =
      internal_static_test_Battle_Player_descriptor.getNestedTypes().get(0);
    internal_static_test_Battle_Player_SkillEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_test_Battle_Player_SkillEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_test_Battle_Skill_descriptor =
      internal_static_test_Battle_descriptor.getNestedTypes().get(1);
    internal_static_test_Battle_Skill_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_test_Battle_Skill_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_test_Element_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_test_Element_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_test_Element_descriptor,
        new java.lang.String[] { "BoolValue", "FloatValue", "DoubleValue", "Int32Value", "Int64Value", "Uint32Value", "Uint64Value", "Sint32Value", "Sint64Value", "Fixed32Value", "Fixed64Value", "Sfixed32Value", "Sfixed64Value", "StringValue", "BytesValue", "Type", "Player", "Skill", "UnionBoolValue", "UnionFloatValue", "UnionDoubleValue", "UnionInt32Value", "UnionInt64Value", "UnionUint32Value", "UnionUint64Value", "UnionSint32Value", "UnionSint64Value", "UnionFixed32Value", "UnionFixed64Value", "UnionSfixed32Value", "UnionSfixed64Value", "UnionStringValue", "UnionBytesValue", "UnionType", "UnionPlayer", "UnionSkill", "BoolValues", "FloatValues", "DoubleValues", "Int32Values", "Int64Values", "Uint32Values", "Uint64Values", "Sint32Values", "Sint64Values", "Fixed32Values", "Fixed64Values", "Sfixed32Values", "Sfixed64Values", "StringValues", "BytesValues", "Types", "Players", "Skills", "Resp", "Union", });
    internal_static_test_Element_Type_descriptor =
      internal_static_test_Element_descriptor.getNestedTypes().get(0);
    internal_static_test_Element_Type_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_test_Element_Type_descriptor,
        new java.lang.String[] { "Id", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
