// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/element.proto

package test;

/**
 * Protobuf enum {@code test.Response}
 */
public enum Response
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>OK = 0;</code>
   */
  OK(0, 0),
  /**
   * <code>NO = 1;</code>
   */
  NO(1, 1),
  UNRECOGNIZED(-1, -1),
  ;

  /**
   * <code>OK = 0;</code>
   */
  public static final int OK_VALUE = 0;
  /**
   * <code>NO = 1;</code>
   */
  public static final int NO_VALUE = 1;


  public final int getNumber() {
    if (index == -1) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  public static Response valueOf(int value) {
    switch (value) {
      case 0: return OK;
      case 1: return NO;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<Response>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      Response> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<Response>() {
          public Response findValueByNumber(int number) {
            return Response.valueOf(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(index);
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return test.ElementDef.getDescriptor()
        .getEnumTypes().get(0);
  }

  private static final Response[] VALUES = values();

  public static Response valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int index;
  private final int value;

  private Response(int index, int value) {
    this.index = index;
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:test.Response)
}

